name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  backend_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Run eslint
        working-directory: ./watchlist-backend
        run: |
          npm install
          npm run eslint
  frontend_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Run eslint
        working-directory: ./watchlist-frontend
        run: |
          npm install
          npm run eslint
  deploy:
    runs-on: ubuntu-20.04
    needs: [backend_pipeline, frontend_pipeline]
    steps:
      - name: Deploy
        # Only run this step if the branch is main
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
